Event director
frmscoe/channel-router-setup-processor pull request #150
Opened 2024-05-31 10:38 UTC by JeanPierreNell

in relation https://github.com/frmscoe/channel-router-setup-processor/issues/135

2024-05-31 10:59 UTC, Justus-at-Tazama approved these changes
![awesome-yes-awesome](https://github.com/frmscoe/channel-router-setup-processor/assets/123470803/508dfc48-175b-41a1-91b4-b7adc319e514)

2024-05-31 13:25 UTC, cshezi submitted a review, later dismissed
JPONFIRE 🚒

2024-05-31 14:18 UTC, Justus-at-Tazama requested changes

2024-06-03 05:11 UTC, Justus-at-Tazama approved these changes

2024-06-03 05:30 UTC, cshezi approved these changes

2024-06-03 06:44 UTC, merged